#pragma once

// Generated by tools/build_lobby_catalog.py from the installed English USFIV
// command lists. See docs/LOBBY_CATALOG.md for evidence and input notation.
// No Windows, ImGui, or game-runtime dependency; valid standalone C++11.
namespace sf4e { namespace LobbyCatalog {

static const int CharacterCount = 44;
static const int StageCount = 30;

struct Ultra { const char* name; const char* input; const char* note; };
struct Fighter { const char* code; const char* name; Ultra ultra[2]; };
struct Stage { const char* code; const char* name; bool versus; };

inline const Fighter* Find(int characterId) {
    static const Fighter fighters[CharacterCount] = {
        {"RYU", "Ryu", {{"Metsu Hadoken", "D DF F D DF F + PPP", ""}, {"Metsu Shoryuken", "D DF F D DF F + KKK", ""}}}, // 0
        {"KEN", "Ken", {{"Shinryuken", "D DF F D DF F + PPP", ""}, {"Guren Senpukyaku", "D DF F D DF F + KKK", ""}}}, // 1
        {"CNL", "Chun-Li", {{"Hosenka", "CHARGE B F B F + KKK", ""}, {"Kikosho", "D DF F D DF F + PPP", ""}}}, // 2
        {"HND", "E. Honda", {{"Ultimate Killer Head Ram", "CHARGE B F B F + PPP", ""}, {"Orochi Breaker", "F DF D DB B F DF D DB B + PPP", ""}}}, // 3
        {"BLK", "Blanka", {{"Lightning Cannonball", "CHARGE B F B F + PPP", "Hold PPP to delay the roll."}, {"Shout of Earth", "CHARGE DB DF DB UF + PPP", "PPP: anti-air. KKK: anti-ground. Hold PPP to delay."}}}, // 4
        {"ZGF", "Zangief", {{"Ultimate Atomic Buster", "720 + PPP", ""}, {"Siberian Blizzard", "AIR 720 + KKK", ""}}}, // 5
        {"GUL", "Guile", {{"Flash Explosion", "CHARGE DB DF DB UF + KKK", ""}, {"Sonic Hurricane", "CHARGE B F B F + PPP", ""}}}, // 6
        {"DSM", "Dhalsim", {{"Yoga Catastrophe", "D DF F D DF F + PPP", ""}, {"Yoga Shangri-La", "AIR D DF F D DF F + KKK", ""}}}, // 7
        {"BSN", "Balrog", {{"Violent Buffalo", "CHARGE B F B F + PPP OR KKK", ""}, {"Dirty Bull", "F DF D DB B F DF D DB B + PPP", ""}}}, // 8
        {"BLR", "Vega", {{"Bloody High Claw", "CHARGE DB DF DB UF + KKK", ""}, {"Splendid Claw", "CHARGE DB F B F + KKK", ""}}}, // 9
        {"SGT", "Sagat", {{"Tiger Destruction", "D DF F D DF F + KKK", ""}, {"Tiger Cannon", "D DF F D DF F + PPP", ""}}}, // 10
        {"VEG", "M. Bison", {{"Nightmare Booster", "CHARGE B F B F + KKK", ""}, {"Psycho Punisher", "D DF F D DF F + KKK", ""}}}, // 11
        {"AGL", "C. Viper", {{"Burst Time", "D DF F D DF F + PPP", ""}, {"Burning Dance", "AIR D DB B D DB B + KKK", ""}}}, // 12
        {"CHB", "Rufus", {{"Space Opera Symphony", "D DF F D DF F + PPP", ""}, {"Big Bang Typhoon", "D DB B D DB B + PPP", ""}}}, // 13
        {"RIC", "El Fuerte", {{"El Fuerte Flying Giga Buster", "D DF F D DF F + KKK", ""}, {"El Fuerte Ultra Spark", "D DB B D DB B + KKK", ""}}}, // 14
        {"JHA", "Abel", {{"Soulless", "D DF F D DF F + PPP", ""}, {"Breathless", "D DF F D DF F + KKK", "Hold KKK to delay; P cancels the charge."}}}, // 15
        {"BOS", "Seth", {{"Tanden Stream", "D DF F D DF F + PPP", ""}, {"Tanden Typhoon", "D DB B D DB B + PPP", ""}}}, // 16
        {"GKI", "Akuma", {{"Wrath of the Raging Demon", "LP LP B LK HP", ""}, {"Demon Armageddon", "U U + KKK", ""}}}, // 17
        {"GKN", "Gouken", {{"Shin Shoryuken", "D DF F D DF F + PPP", ""}, {"Denjin Hadoken", "D DF F D DF F + KKK", "Hold KKK to charge."}}}, // 18
        {"HWK", "T. Hawk", {{"Raging Typhoon", "720 + PPP", ""}, {"Raging Slash", "F DF D DB B F DF D DB B + KKK", ""}}}, // 19
        {"CMY", "Cammy", {{"Gyro Drive Smasher", "D DF F D DF F + KKK", ""}, {"CQC (Cammy Quick Combination)", "D DB B D DB B + PPP", "Counter: requires an eligible incoming attack."}}}, // 20
        {"FLN", "Fei Long", {{"Rekkashingeki", "D DF F D DF F + PPP", ""}, {"Gekirinken", "D DF F D DF F + KKK", "Counter: requires an eligible incoming attack."}}}, // 21
        {"DJY", "Dee Jay", {{"Sobat Festival", "CHARGE B F B F + KKK", ""}, {"Climax Beat", "CHARGE DB DF DB UF + PPP", ""}}}, // 22
        {"SKR", "Sakura", {{"Haru Ranman", "D DB B D DB B + KKK", ""}, {"Shinku Hadoken", "D DF F D DF F + PPP", "KKK instead: Shinku Tengyo Hadoken (anti-air)."}}}, // 23
        {"ROS", "Rose", {{"Illusion Spark", "D DF F D DF F + PPP", ""}, {"Soul Satellite", "D DB B D DB B + KKK", ""}}}, // 24
        {"GEN", "Gen", {{"Zetsuei / Ryukoha", "D DF F D DF F + PPP", "Mantis: Zetsuei. Crane: same motion + KKK for Ryukoha."}, {"Shitenketsu / Teiga", "D DB B D DB B + PPP", "Mantis: Shitenketsu. Crane: AIR D DF F D DF F + KKK for Teiga."}}}, // 25
        {"DAN", "Dan", {{"Shisso Buraiken", "D DF F D DF F + PPP", ""}, {"Haoh Gadoken", "D DF F D DF F + KKK", ""}}}, // 26
        {"GUY", "Guy", {{"Bushin Goraisenpujin", "D DF F D DF F + KKK", ""}, {"Bushin Muso Renge", "NEAR F DF D DB B F DF D DB B + PPP", ""}}}, // 27
        {"CDY", "Cody", {{"Final Destruction", "D DF F D DF F + PPP", ""}, {"Last Dread Dust", "D DB B D DB B + PPP", ""}}}, // 28
        {"IBK", "Ibuki", {{"Yoroitoshi", "F DF D DB B F DF D DB B + PPP", ""}, {"Hashinsho", "D DF F D DF F + KKK", ""}}}, // 29
        {"MKT", "Makoto", {{"Seichusen Godanzuki", "D DF F D DF F + PPP", ""}, {"Abare Tosanami", "D DF F D DF F + KKK", ""}}}, // 30
        {"DDL", "Dudley", {{"Rolling Thunder", "D DF F D DF F + KKK", ""}, {"Corkscrew Cross", "D DF F D DF F + PPP", ""}}}, // 31
        {"ADN", "Adon", {{"Jaguar Revolver", "D DB B D DB B + KKK", ""}, {"Jaguar Avalanche", "D DF F D DF F + KKK", ""}}}, // 32
        {"HKN", "Hakan", {{"Oil Coaster", "NEAR 720 + PPP", ""}, {"Oil Combination Hold", "D D D + KKK", ""}}}, // 33
        {"JRI", "Juri", {{"Feng Shui Engine", "D DF F D DF F + PPP", ""}, {"Kaisen Dankairaku", "D DF F D DF F + KKK", ""}}}, // 34
        {"YUN", "Yun", {{"You Hou", "D DF F D DF F + PPP", "Unavailable during Genei Jin."}, {"Sorai Rengeki", "D DF F D DF F + KKK", "Unavailable during Genei Jin."}}}, // 35
        {"YAN", "Yang", {{"Raishin Mahhaken", "D DF F D DF F + PPP", ""}, {"Tenshin Senkyutai", "D DF F D DF F + KKK", ""}}}, // 36
        {"RYX", "Evil Ryu", {{"Metsu Hadoken", "D DF F D DF F + PPP", "Hold PPP to charge."}, {"Messatsu-Goshoryu", "D DF F D DF F + KKK", ""}}}, // 37
        {"GKX", "Oni", {{"Meido Gohado", "D DF F D DF F + PPP", "AIR + PPP: Messatsu-Gozanku. Ground + KKK: Messatsu-Gotenha."}, {"Tenchi Sokaigen", "F DF D DB B F DF D DB B + PPP", ""}}}, // 38
        {"RLN", "Rolento", {{"Patriot Sweeper", "D DF F D DF F + PPP", ""}, {"Take No Prisoners", "D DF F D DF F + KKK", ""}}}, // 39
        {"ELN", "Elena", {{"Brave Dance", "D DF F D DF F + KKK", ""}, {"Healing", "D DF F D DF F + PPP", "Press PPP again to stop healing."}}}, // 40
        {"PSN", "Poison", {{"Love Storm", "D DF F D DF F + PPP", ""}, {"Poison Kiss", "NEAR F DF D DB B F DF D DB B + PPP", ""}}}, // 41
        {"HUG", "Hugo", {{"Gigas Breaker", "NEAR 720 + PPP", ""}, {"Megaton Press", "D DF F D DF F + KKK", ""}}}, // 42
        {"DCP", "Decapre", {{"Psycho Stream", "CHARGE B F B F + PPP", ""}, {"DCM", "CHARGE B F B F + KKK", "Anti-air: CHARGE DB DF DB UF + KKK. Heavy trajectory: same + PPP."}}}, // 43
    };
    return characterId >= 0 && characterId < CharacterCount ? &fighters[characterId] : nullptr;
}

// Edition values are the engine IDs: SFIV=13, Super=1, AE=2, 2012=4, Ultra=14.
// Omega (16) is deliberately unverified; nullptr permits an explicit reference label.
inline const Ultra* FindUltra(int characterId, int ultraIndex, int edition = 14) {
    const Fighter* fighter = Find(characterId);
    if (!fighter || ultraIndex < 0 || ultraIndex > 1) return nullptr;
    if (edition != 13 && edition != 1 && edition != 2 && edition != 4 && edition != 14) return nullptr;
    if (edition == 13 && ultraIndex != 0) return nullptr;
    static const unsigned int validEditionMask[CharacterCount] = {
        90134u, 90134u, 90134u, 90134u, 90134u, 90134u, 90134u, 90134u,
        90134u, 90134u, 90134u, 90134u, 90134u, 90134u, 90134u, 90134u,
        90134u, 90134u, 90134u, 81942u, 90134u, 90134u, 81942u, 90134u,
        90134u, 90134u, 90134u, 81942u, 81942u, 81942u, 81942u, 81942u,
        81942u, 81942u, 81942u, 81940u, 81940u, 81940u, 81940u, 81920u,
        81920u, 81920u, 81920u, 81920u,
    };
    if (!(validEditionMask[characterId] & (1u << edition))) return nullptr;
    struct Override { int edition, character, ultra; Ultra move; };
    static const Override overrides[] = {
        {1, 3, 1, {"Orochi Breaker", "720 + PPP", ""}},
        {1, 7, 1, {"Yoga Shangri-La", "AIR D DF F D DF F + PPP", ""}},
        {1, 8, 1, {"Dirty Bull", "720 + PPP", ""}},
        {1, 19, 1, {"Raging Slash", "F DF D DB B F DF D DB B + PPP", ""}},
        {1, 24, 1, {"Soul Satellite", "D DB B D DB B + PPP", ""}},
        {2, 7, 1, {"Yoga Shangri-La", "AIR D DF F D DF F + PPP", ""}},
        {2, 11, 1, {"Psycho Punisher", "CHARGE B F B F + PPP", ""}},
        {2, 19, 1, {"Raging Slash", "F DF D DB B F DF D DB B + PPP", ""}},
        {2, 24, 1, {"Soul Satellite", "D DB B D DB B + PPP", ""}},
        {2, 38, 1, {"Tenchi Sokaigen", "B DB D DF F B DB D DF F + PPP", ""}},
        {4, 7, 1, {"Yoga Shangri-La", "AIR D DF F D DF F + PPP", ""}},
        {4, 11, 1, {"Psycho Punisher", "CHARGE B F B F + PPP", ""}},
        {4, 19, 1, {"Raging Slash", "F DF D DB B F DF D DB B + PPP", ""}},
        {4, 24, 1, {"Soul Satellite", "D DB B D DB B + PPP", ""}},
        {4, 38, 1, {"Tenchi Sokaigen", "B DB D DF F B DB D DF F + PPP", ""}},
    };
    for (const Override& value : overrides)
        if (value.edition == edition && value.character == characterId && value.ultra == ultraIndex) return &value.move;
    return &fighter->ultra[ultraIndex];
}

inline const Stage* FindStage(int stageId) {
    static const Stage stages[StageCount] = {
        {"TRN", "Training Stage", true}, // 0
        {"CHN", "Crowded Downtown", true}, // 1
        {"USA", "Drive-in at Night", true}, // 2
        {"RUS", "Snowy Rail Yard", true}, // 3
        {"BRA", "Inland Jungle", true}, // 4
        {"AFR", "Small Airfield", true}, // 5
        {"VIE", "Beautiful Bay", true}, // 6
        {"EUR", "Cruise Ship Stern", true}, // 7
        {"RVR", "Overpass", true}, // 8
        {"VCN", "Volcanic Rim", true}, // 9
        {"SCO", "Historic Distillery", true}, // 10
        {"JPN", "Old Temple", true}, // 11
        {"LAB", "Secret Laboratory", true}, // 12
        {"IND", "Exciting Street Scene", true}, // 13
        {"KOR", "Festival At The Old Temple", true}, // 14
        {"BLD", "Skyscraper Under Construction", true}, // 15
        {"CNX", "Run-down Back Alley", true}, // 16
        {"BRX", "Pitch-black Jungle", true}, // 17
        {"VNX", "Morning Mist Bay", true}, // 18
        {"JPX", "Deserted Temple", true}, // 19
        {"AFX", "Solar Eclipse", true}, // 20
        {"LBX", "Crumbling Laboratory", true}, // 21
        {"GAS", "Car Destruction", false}, // 22
        {"SCX", "Barrel Destruction", false}, // 23
        {"DET", "The Pitstop 109", true}, // 24
        {"ELV", "Cosmic Elevator", true}, // 25
        {"HFP", "The Half Pipe", true}, // 26
        {"MAD", "Mad Gear Hideout", true}, // 27
        {"BFU", "Blast Furnace", true}, // 28
        {"JUR", "Jurassic Era Research Facility", true}, // 29
    };
    return stageId >= 0 && stageId < StageCount ? &stages[stageId] : nullptr;
}

// Shared UI palette; these are fork design tokens, not sampled game pixels.
struct RGB { unsigned char r, g, b; };
inline RGB UltraColor(int selection) {
    static const RGB colors[3] = { {255, 117, 51}, {67, 173, 255}, {187, 115, 255} };
    return colors[selection >= 0 && selection < 3 ? selection : 0];
}

}} // namespace sf4e::LobbyCatalog
